---
- hosts: haproxy
  become: true
  tasks:
    - name: Pull haproxy Docker image 
      docker_image:
        name: haproxy
        source: pull
        tag: latest

    - name: Run haproxy service on port 80
      docker_container:
        name: haproxy
        image: ghenac/haproxy:latest #Change with the actuall docker image
        ports:
          - "80:80"
        state: started   