---
# - hosts: haproxy
#   become: true
#   tasks:     
    - name: update_cache
      apt:
        update_cache: yes

    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: copy haproxy.cfg 
      template:
        src: ../templates/haproxy.cfg.j2   #try putting the whole correct path
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted