---
# - hosts: backend
#   become: true
#   tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image for auth
      docker_image:
        name: pablop115/auth
        source: pull
        tag: latest
      when: inventory_hostname == 'backend_auth'

    - name: Run auth service
      docker_container:
        name: auth
        image: pablop115/auth:latest #Changed with the actuall docker image
        ports:
          - "3001:3001"
        state: started
      when: inventory_hostname == 'backend_auth'

    - name: Pull Docker image for discounts
      docker_image:
        name: pablop115/discounts
        source: pull
        tag: latest
      when: inventory_hostname == 'backend_discounts'
    - name: Run discounts service
      docker_container:
        name: discounts
        image: pablop115/discounts:latest #Changed with the actuall docker image
        ports:
          - "3002:3002"
        state: started
      when: inventory_hostname == 'backend_discounts'
      

    - name: Pull Docker image for items
      docker_image:
        name: pablop115/items
        source: pull
        tag: latest
      when: inventory_hostname == 'backend_items'

    - name: Run items service
      docker_container:
        name: items
        image: pablop115/items:latest #Changed with the actuall docker image
        ports:
          - "3003:3003"
        state: started
      when: inventory_hostname == 'backend_items'