---
- hosts: backend
  become: true
  tasks:
    - name: Pull Docker image for auth
      docker_image:
        name: backend-auth
        source: pull
        tag: latest

    - name: Run auth service
      docker_container:
        name: backend-auth
        image: ghenac/backend-auth:latest #Changed with the actuall docker image
        ports:
          - "3001:3001"
        state: started

    - name: Pull Docker image for discounts
      docker_image:
        name: backend-discounts
        source: pull
        tag: latest

    - name: Run discounts service
      docker_container:
        name: backend-discounts
        image: ghenac/backend-discounts:latest #Changed with the actuall docker image
        ports:
          - "3002:3002"
        state: started

    - name: Pull Docker image for items
      docker_image:
        name: backend-items
        source: pull
        tag: latest

    - name: Run items service
      docker_container:
        name: backend-items
        image: ghenac/backend-items:latest #Changed with the actuall docker image
        ports:
          - "3003:3003"
        state: started